name: Test edge

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem update --system --no-document
      - run: gem install bundler --no-document
      - run: bundle config set path vendor/bundle
      - run: bundle install --jobs=4 --retry=3
      - run: bundle add rubocop --git https://github.com/rubocop-hq/rubocop.git
      - run: bundle exec rake
