name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem update --system --no-document
      - run: gem install bundler --no-document
      - run: bundle config set path vendor/bundle
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rake
